package com.example.mongousage.io;

import com.example.mongousage.model.UsageReport;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

public class UsageSummaryHtmlWriter {
    public void write(UsageReport report, Path outputFile) throws IOException {
        Files.createDirectories(outputFile.toAbsolutePath().getParent());
        UsageSummaryData summary = UsageSummaryData.from(report);
        Files.writeString(outputFile, render(summary), StandardCharsets.UTF_8);
    }

    private String render(UsageSummaryData summary) {
        StringBuilder html = new StringBuilder();
        html.append("<!doctype html>\n")
                .append("<html lang=\"zh-CN\">\n")
                .append("<head>\n")
                .append("  <meta charset=\"utf-8\">\n")
                .append("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n")
                .append("  <title>MongoDB Usage Summary</title>\n")
                .append("  <style>\n")
                .append("    :root { color-scheme: light; font-family: Arial, 'PingFang SC', 'Microsoft YaHei', sans-serif; }\n")
                .append("    body { margin: 0; background: #f6f8fb; color: #172033; }\n")
                .append("    main { max-width: 1180px; margin: 0 auto; padding: 32px 24px 48px; }\n")
                .append("    h1 { margin: 0 0 8px; font-size: 28px; }\n")
                .append("    h2 { margin: 32px 0 12px; font-size: 20px; }\n")
                .append("    .subtitle { margin: 0 0 24px; color: #5b677a; }\n")
                .append("    table { width: 100%; border-collapse: collapse; background: #fff; border: 1px solid #d9e0ea; }\n")
                .append("    th, td { padding: 10px 12px; border-bottom: 1px solid #e4e9f0; text-align: left; vertical-align: top; }\n")
                .append("    th { background: #1f4e78; color: #fff; font-weight: 700; }\n")
                .append("    tr:nth-child(even) td { background: #fafbfd; }\n")
                .append("    .key { width: 260px; font-weight: 700; }\n")
                .append("    .mono { font-family: Menlo, Consolas, monospace; white-space: pre-wrap; word-break: break-word; }\n")
                .append("    .badge { display: inline-block; min-width: 42px; padding: 2px 8px; border-radius: 4px; text-align: center; font-size: 12px; font-weight: 700; }\n")
                .append("    .yes { background: #dff3e4; color: #1d6b35; }\n")
                .append("    .no { background: #eef2f6; color: #51606f; }\n")
                .append("  </style>\n")
                .append("</head>\n")
                .append("<body>\n")
                .append("<main>\n")
                .append("  <h1>MongoDB Usage Summary</h1>\n")
                .append("  <p class=\"subtitle\">Generated by mongo-usage-collector summarize.</p>\n");

        appendExecutiveSummary(html, summary);
        appendFeatureSummary(html, summary);
        appendTopCollections(html, summary);
        appendTopQueryShapes(html, summary);
        appendRisks(html, summary);

        html.append("</main>\n")
                .append("</body>\n")
                .append("</html>\n");
        return html.toString();
    }

    private void appendExecutiveSummary(StringBuilder html, UsageSummaryData summary) {
        html.append("  <h2>Executive Summary</h2>\n")
                .append("  <table>\n")
                .append("    <tbody>\n");
        for (UsageSummaryData.KeyValue row : summary.executiveSummary()) {
            html.append("      <tr><td class=\"key\">").append(escape(row.key())).append("</td><td>")
                    .append(escape(row.value())).append("</td></tr>\n");
        }
        html.append("    </tbody>\n")
                .append("  </table>\n");
    }

    private void appendFeatureSummary(StringBuilder html, UsageSummaryData summary) {
        html.append("  <h2>Feature Summary</h2>\n")
                .append("  <table>\n")
                .append("    <thead><tr><th>Feature</th><th>Detected</th><th>Evidence</th></tr></thead>\n")
                .append("    <tbody>\n");
        for (UsageSummaryData.FeatureItem row : summary.featureSummary()) {
            String badgeClass = row.detected() ? "yes" : "no";
            String status = row.detected() ? "Yes" : "No";
            html.append("      <tr><td>").append(escape(row.feature())).append("</td><td><span class=\"badge ")
                    .append(badgeClass).append("\">").append(status).append("</span></td><td>")
                    .append(escape(row.evidence())).append("</td></tr>\n");
        }
        html.append("    </tbody>\n")
                .append("  </table>\n");
    }

    private void appendTopCollections(StringBuilder html, UsageSummaryData summary) {
        html.append("  <h2>Top Collections</h2>\n")
                .append("  <table>\n")
                .append("    <thead><tr><th>Namespace</th><th>Type</th><th>Documents</th><th>Storage Size</th><th>Index Size</th><th>Index Count</th></tr></thead>\n")
                .append("    <tbody>\n");
        for (UsageSummaryData.CollectionItem row : summary.topCollections()) {
            html.append("      <tr><td>").append(escape(row.namespace())).append("</td><td>")
                    .append(escape(row.type())).append("</td><td>").append(row.documents()).append("</td><td>")
                    .append(row.storageSize()).append("</td><td>").append(row.indexSize()).append("</td><td>")
                    .append(row.indexCount()).append("</td></tr>\n");
        }
        html.append("    </tbody>\n")
                .append("  </table>\n");
    }

    private void appendTopQueryShapes(StringBuilder html, UsageSummaryData summary) {
        html.append("  <h2>Top Query Shapes</h2>\n")
                .append("  <table>\n")
                .append("    <thead><tr><th>Namespace</th><th>Operation</th><th>Samples</th><th>Avg ms</th><th>Max ms</th><th>Features</th><th>Shape</th></tr></thead>\n")
                .append("    <tbody>\n");
        for (UsageSummaryData.QueryShapeItem row : summary.topQueryShapes()) {
            html.append("      <tr><td>").append(escape(row.namespace())).append("</td><td>")
                    .append(escape(row.operation())).append("</td><td>").append(row.samples()).append("</td><td>")
                    .append(row.avgMillis()).append("</td><td>").append(row.maxMillis()).append("</td><td>")
                    .append(escape(row.features())).append("</td><td class=\"mono\">")
                    .append(escape(row.shape())).append("</td></tr>\n");
        }
        html.append("    </tbody>\n")
                .append("  </table>\n");
    }

    private void appendRisks(StringBuilder html, UsageSummaryData summary) {
        html.append("  <h2>Risks</h2>\n")
                .append("  <table>\n")
                .append("    <thead><tr><th>Severity</th><th>Area</th><th>Observation</th><th>Suggested Review</th></tr></thead>\n")
                .append("    <tbody>\n");
        for (UsageSummaryData.RiskItem row : summary.risks()) {
            html.append("      <tr><td>").append(escape(row.severity())).append("</td><td>")
                    .append(escape(row.area())).append("</td><td>").append(escape(row.observation()))
                    .append("</td><td>").append(escape(row.suggestedReview())).append("</td></tr>\n");
        }
        html.append("    </tbody>\n")
                .append("  </table>\n");
    }

    private String escape(Object value) {
        if (value == null) {
            return "";
        }
        return String.valueOf(value)
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;")
                .replace("'", "&#39;");
    }
}
