package com.example.mongousage.compat;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Optional;

public final class MongoCompatTestCaseReference {
    private static final Map<String, Reference> REFERENCES = parseReferences();

    private MongoCompatTestCaseReference() {
    }

    public static Optional<Reference> find(String id) {
        return Optional.ofNullable(REFERENCES.get(id));
    }

    public static Map<String, Reference> all() {
        return REFERENCES;
    }

    private static Map<String, Reference> parseReferences() {
        Map<String, Reference> references = new LinkedHashMap<>();
        for (String line : RAW_REFERENCES.strip().split("\\R")) {
            if (line.isBlank()) {
                continue;
            }
            String[] parts = line.split("\t", 3);
            references.put(parts[1], new Reference(Integer.parseInt(parts[0]), parts[2]));
        }
        return Map.copyOf(references);
    }

    public record Reference(int number, String mongoshCommand) {
        public String formattedNumber() {
            return "%03d".formatted(number);
        }
    }

    private static final String RAW_REFERENCES = """
            1	schema-json-validator	db.createCollection("orders", { validator: { $jsonSchema: { bsonType: "object", required: ["orderNo","customerId","status","total","createdAt","lines"] } } })
            2	schema-validation-reject	db.orders.insertOne({ orderNo: "BAD-1" })
            3	schema-list-collections	db.getCollectionNames()
            4	schema-validator-options-readable	db.getCollectionInfos({ name: "orders" })
            5	schema-valid-document-accepted	db.orders.insertOne({ orderNo: "VALID-SCHEMA", customerId: 1, status: "new", total: 1.0, createdAt: new Date(), lines: [{ sku: "SKU-VALID", qty: 1 }] })
            6	schema-missing-required-field-rejected	db.orders.insertOne({ orderNo: "BAD-1" })
            7	schema-invalid-enum-rejected	db.orders.insertOne({ orderNo: "BAD-ENUM", customerId: 1, status: "bad", total: 1, createdAt: new Date(), lines: [] })
            8	schema-invalid-array-type-rejected	db.orders.insertOne({ orderNo: "BAD-ARRAY", customerId: 1, status: "new", total: 1, createdAt: new Date(), lines: "not-array" })
            9	crud-insert-find-update-delete	db.customers.insertOne(...); db.customers.findOne(...); db.customers.updateOne(...); db.customers.findOneAndUpdate(...); db.customers.deleteOne(...)
            10	crud-bulk-write	db.customers.bulkWrite([{ insertOne: {...} }, { updateOne: {...} }, { updateOne: { upsert: true, ... } }])
            11	crud-insert-one	db.scratch.insertOne({ kind: "insert-one", score: 1 })
            12	crud-insert-many	db.scratch.insertMany([{ kind: "insert-many-a" }, { kind: "insert-many-b" }])
            13	crud-find-one	db.scratch.findOne({ kind: "seed" })
            14	crud-count-documents	db.scratch.countDocuments({ kind: "seed" })
            15	crud-estimated-count	db.scratch.estimatedDocumentCount()
            16	crud-distinct	db.customers.distinct("region")
            17	crud-update-one-set	db.scratch.updateOne({ kind: "seed" }, { $set: { marker: "set" } })
            18	crud-update-many-inc	db.scratch.updateMany({ score: { $exists: true } }, { $inc: { score: 1 } })
            19	crud-replace-one	db.scratch.replaceOne({ kind: "replace-target" }, { kind: "replace-target", score: 99 })
            20	crud-delete-one	db.scratch.deleteOne({ kind: "delete-one-target" })
            21	crud-delete-many	db.scratch.deleteMany({ kind: "delete-many-target" })
            22	crud-upsert-one	db.scratch.updateOne({ kind: "upsert-target" }, { $set: { score: 1 } }, { upsert: true })
            23	crud-find-one-and-delete	db.scratch.findOneAndDelete({ kind: "find-delete-target" })
            24	crud-find-one-and-replace	db.scratch.findOneAndReplace({ kind: "find-replace-target" }, { kind: "find-replace-target", score: 55 })
            25	crud-ordered-bulk-write	db.scratch.bulkWrite([{ insertOne: { document: { kind: "ordered-bulk" } } }], { ordered: true })
            26	crud-unordered-bulk-write	db.scratch.bulkWrite([{ insertOne: { document: { kind: "unordered-bulk" } } }], { ordered: false })
            27	query-filter-sort-project	db.orders.find({ total: { $gte: 30 }, status: "paid" }, { orderNo: 1, total: 1, _id: 0 }).sort({ createdAt: -1 }).skip(1).limit(5)
            28	query-array-element	db.orders.countDocuments({ lines: { $elemMatch: { sku: "SKU-1", qty: { $gte: 1 } } } })
            29	query-eq	db.orders.countDocuments({ status: { $eq: "paid" } })
            30	query-ne	db.orders.countDocuments({ status: { $ne: "paid" } })
            31	query-gt	db.orders.countDocuments({ total: { $gt: 50 } })
            32	query-gte	db.orders.countDocuments({ total: { $gte: 50 } })
            33	query-lt	db.orders.countDocuments({ total: { $lt: 50 } })
            34	query-lte	db.orders.countDocuments({ total: { $lte: 50 } })
            35	query-in	db.orders.countDocuments({ status: { $in: ["paid", "new"] } })
            36	query-nin	db.orders.countDocuments({ status: { $nin: ["cancelled"] } })
            37	query-and	db.orders.countDocuments({ $and: [{ status: "paid" }, { total: { $gte: 20 } }] })
            38	query-or	db.orders.countDocuments({ $or: [{ status: "paid" }, { status: "new" }] })
            39	query-nor	db.orders.countDocuments({ $nor: [{ status: "missing" }] })
            40	query-exists	db.orders.countDocuments({ createdAt: { $exists: true } })
            41	query-type	db.orders.countDocuments({ orderNo: { $type: "string" } })
            42	query-regex	db.orders.countDocuments({ orderNo: { $regex: "^COMPAT-" } })
            43	query-all	db.orders.countDocuments({ tags: { $all: ["compat", "order"] } })
            44	query-size	db.orders.countDocuments({ lines: { $size: 1 } })
            45	query-elem-match	db.orders.countDocuments({ lines: { $elemMatch: { sku: "SKU-1", qty: { $gte: 1 } } } })
            46	query-dot-path	db.orders.countDocuments({ "lines.sku": "SKU-1" })
            47	query-not	db.orders.countDocuments({ total: { $not: { $lt: 0 } } })
            48	query-mod	db.orders.countDocuments({ customerId: { $mod: [2, 0] } })
            49	query-date-range	db.orders.countDocuments({ createdAt: { $lte: new Date() } })
            50	query-sort-ascending	db.orders.find().sort({ createdAt: 1 }).limit(1)
            51	query-sort-descending	db.orders.find().sort({ createdAt: -1 }).limit(1)
            52	query-skip-limit	db.orders.find().skip(1).limit(1)
            53	query-expr	db.orders.countDocuments({ $expr: { $gte: ["$total", 50] } })
            54	query-json-schema	db.orders.countDocuments({ $jsonSchema: { bsonType: "object", required: ["orderNo", "customerId"] } })
            55	query-bits-all-set	db.scratch.countDocuments({ flags: { $bitsAllSet: 1 } })
            56	query-bits-any-clear	db.scratch.countDocuments({ flags: { $bitsAnyClear: 4 } })
            57	query-where	db.orders.countDocuments({ $where: function() { return this.total >= 0; } })
            58	query-collation-case-insensitive	db.orders.find({ caseName: "compat-case" }).collation({ locale: "en", strength: 2 }).limit(1)
            59	query-natural-sort	db.orders.find().sort({ $natural: 1 }).limit(1)
            60	query-min-max	db.scratch.find().hint({ score: 1 }).min({ score: 0 }).max({ score: 1000 }).limit(1)
            61	update-inc	db.scratch.updateOne({ kind: "update-target" }, { $inc: { score: 1 } })
            62	update-mul	db.scratch.updateOne({ kind: "update-target" }, { $mul: { score: 2 } })
            63	update-min	db.scratch.updateOne({ kind: "update-target" }, { $min: { score: 1 } })
            64	update-max	db.scratch.updateOne({ kind: "update-target" }, { $max: { score: 99 } })
            65	update-rename	db.scratch.updateOne({ kind: "update-target" }, { $rename: { renameSource: "renameTarget" } })
            66	update-unset	db.scratch.updateOne({ kind: "update-target" }, { $unset: { temporary: "" } })
            67	update-current-date	db.scratch.updateOne({ kind: "update-target" }, { $currentDate: { touchedAt: true } })
            68	update-add-to-set	db.scratch.updateOne({ kind: "update-target" }, { $addToSet: { tags: "deduped" } })
            69	update-push-each-sort-slice	db.scratch.updateOne({ kind: "update-target" }, { $push: { scores: { $each: [5, 1, 3], $sort: -1, $slice: 3 } } })
            70	update-pull	db.scratch.updateOne({ kind: "update-target" }, { $pull: { tags: "remove-me" } })
            71	update-pop	db.scratch.updateOne({ kind: "update-target" }, { $pop: { scores: 1 } })
            72	update-bit	db.scratch.updateOne({ kind: "update-target" }, { $bit: { flags: { or: 2 } } })
            73	update-array-filter	db.scratch.updateOne({ kind: "update-target" }, { $set: { "lineItems.$[item].reviewed": true } }, { arrayFilters: [{ "item.qty": { $gte: 2 } }] })
            74	update-positional	db.scratch.updateOne({ kind: "update-target", "lineItems.sku": "SKU-2" }, { $set: { "lineItems.$.matched": true } })
            75	update-pipeline	db.scratch.updateOne({ kind: "update-target" }, [{ $set: { pipelineScore: { $add: ["$score", 1] } } }])
            76	index-compound-unique-ttl	db.orders.createIndex({ customerId: 1, status: 1, createdAt: -1 }); db.customers.createIndex({ email: 1 }, { unique: true }); db.orders.createIndex({ expiresAt: 1 }, { expireAfterSeconds: 3600 })
            77	index-hint-explain	db.orders.explain().find({ region: "cn-east" }).hint({ region: 1, total: -1 })
            78	index-list-indexes	db.orders.getIndexes()
            79	index-single-field	db.scratch.createIndex({ score: 1 })
            80	index-compound-order	db.scratch.createIndex({ kind: 1, score: -1 })
            81	index-unique-constraint	db.scratch.createIndex({ uniqueKey: 1 }, { unique: true, sparse: true })
            82	index-ttl-present	db.scratch.createIndex({ expireAt: 1 }, { expireAfterSeconds: 600 })
            83	index-partial-filter	db.scratch.createIndex({ partialScore: 1 }, { partialFilterExpression: { partialScore: { $exists: true } } })
            84	index-sparse	db.scratch.createIndex({ sparseField: 1 }, { sparse: true })
            85	index-text-search	db.scratch.createIndex({ description: "text" }); db.scratch.find({ $text: { $search: "compatibility" } })
            86	index-hashed	db.scratch.createIndex({ kind: "hashed" })
            87	index-wildcard	db.scratch.createIndex({ "$**": 1 })
            88	index-collation	db.scratch.createIndex({ localeName: 1 }, { collation: { locale: "en" } })
            89	index-drop-index	db.scratch.createIndex({ dropMe: 1 }); db.scratch.dropIndex("dropMe_1")
            90	index-recreate-index	db.scratch.createIndex({ recreateMe: 1 }); db.scratch.dropIndex("recreateMe_1"); db.scratch.createIndex({ recreateMe: 1 })
            91	aggregation-group-sort	db.orders.aggregate([{ $match: { status: "paid" } }, { $group: { _id: "$region", count: { $sum: 1 }, revenue: { $sum: "$total" } } }, { $sort: { count: -1 } }])
            92	aggregation-lookup	db.orders.aggregate([{ $match: { orderNo: "COMPAT-1" } }, { $lookup: { from: "customers", localField: "customerId", foreignField: "customerId", as: "customer" } }])
            93	aggregation-facet	db.orders.aggregate([{ $facet: { byStatus: [{ $group: { _id: "$status", count: { $sum: 1 } } }], highValue: [{ $match: { total: { $gte: 80 } } }] } }])
            94	aggregation-match	db.orders.aggregate([{ $match: { status: "paid" } }])
            95	aggregation-project	db.orders.aggregate([{ $project: { orderNo: 1, _id: 0 } }])
            96	aggregation-add-fields	db.orders.aggregate([{ $addFields: { compatFlag: true } }])
            97	aggregation-set	db.orders.aggregate([{ $set: { compatSet: true } }])
            98	aggregation-unset	db.orders.aggregate([{ $unset: "region" }])
            99	aggregation-limit	db.orders.aggregate([{ $limit: 5 }])
            100	aggregation-skip	db.orders.aggregate([{ $skip: 1 }, { $limit: 5 }])
            101	aggregation-sort	db.orders.aggregate([{ $sort: { total: -1 } }])
            102	aggregation-count	db.orders.aggregate([{ $count: "count" }])
            103	aggregation-group-avg	db.orders.aggregate([{ $group: { _id: "$status", avgTotal: { $avg: "$total" } } }])
            104	aggregation-group-min	db.orders.aggregate([{ $group: { _id: "$status", minTotal: { $min: "$total" } } }])
            105	aggregation-group-max	db.orders.aggregate([{ $group: { _id: "$status", maxTotal: { $max: "$total" } } }])
            106	aggregation-group-addToSet	db.orders.aggregate([{ $group: { _id: "$status", regions: { $addToSet: "$region" } } }])
            107	aggregation-group-push	db.orders.aggregate([{ $group: { _id: "$status", orders: { $push: "$orderNo" } } }])
            108	aggregation-unwind	db.orders.aggregate([{ $unwind: "$lines" }])
            109	aggregation-bucket	db.orders.aggregate([{ $bucket: { groupBy: "$total", boundaries: [0, 50, 100, 200], default: "other" } }])
            110	aggregation-sort-by-count	db.orders.aggregate([{ $sortByCount: "$status" }])
            111	aggregation-replace-root	db.orders.aggregate([{ $replaceRoot: { newRoot: { orderNo: "$orderNo", status: "$status" } } }])
            112	aggregation-sample	db.orders.aggregate([{ $sample: { size: 3 } }])
            113	aggregation-date-to-string	db.orders.aggregate([{ $project: { day: { $dateToString: { format: "%Y-%m-%d", date: "$createdAt" } } } }])
            114	aggregation-cond	db.orders.aggregate([{ $project: { bucket: { $cond: [{ $gte: ["$total", 50] }, "high", "low"] } } }])
            115	aggregation-if-null	db.orders.aggregate([{ $project: { safeRegion: { $ifNull: ["$region", "unknown"] } } }])
            116	aggregation-map	db.orders.aggregate([{ $project: { lineSkus: { $map: { input: "$lines", as: "line", in: "$$line.sku" } } } }])
            117	aggregation-filter	db.orders.aggregate([{ $project: { largeLines: { $filter: { input: "$lines", as: "line", cond: { $gte: ["$$line.qty", 2] } } } } }])
            118	aggregation-reduce	db.orders.aggregate([{ $project: { tagText: { $reduce: { input: "$tags", initialValue: "", in: { $concat: ["$$value", "$$this"] } } } } }])
            119	aggregation-to-decimal	db.orders.aggregate([{ $project: { decimalTotal: { $toDecimal: "$total" } } }])
            120	aggregation-convert	db.orders.aggregate([{ $project: { stringTotal: { $convert: { input: "$total", to: "string", onError: "", onNull: "" } } } }])
            121	aggregation-regex-match	db.orders.aggregate([{ $project: { matched: { $regexMatch: { input: "$orderNo", regex: "^COMPAT-" } } } }])
            122	aggregation-date-trunc	db.orders.aggregate([{ $project: { day: { $dateTrunc: { date: "$createdAt", unit: "day" } } } }])
            123	aggregation-union-with	db.orders.aggregate([{ $limit: 1 }, { $unionWith: { coll: "customers", pipeline: [{ $limit: 1 }] } }])
            124	aggregation-graph-lookup	db.categories.aggregate([{ $match: { _id: "leaf" } }, { $graphLookup: { from: "categories", startWith: "$parent", connectFromField: "parent", connectToField: "_id", as: "ancestors" } }])
            125	aggregation-out	db.orders.aggregate([{ $match: { status: "paid" } }, { $out: "agg_out_orders" }])
            126	aggregation-merge	db.orders.aggregate([{ $match: { status: "paid" } }, { $project: { _id: "$orderNo", status: 1 } }, { $merge: { into: "agg_merge_orders", whenMatched: "replace", whenNotMatched: "insert" } }])
            127	aggregation-set-window-fields	db.orders.aggregate([{ $setWindowFields: { partitionBy: "$status", sortBy: { createdAt: 1 }, output: { runningTotal: { $sum: "$total", window: { documents: ["unbounded", "current"] } } } } }])
            128	collection-create-view	db.createView("orders_paid_view", "orders", [{ $match: { status: "paid" } }])
            129	collection-rename	db.rename_source.renameCollection("rename_target")
            130	collection-capped	db.createCollection("capped_events", { capped: true, size: 1048576, max: 100 })
            131	collection-timeseries	db.createCollection("ts_metrics", { timeseries: { timeField: "ts", metaField: "metadata", granularity: "seconds" } })
            132	collection-collmod-validator	db.runCommand({ collMod: "collmod_target", validator: { $jsonSchema: { bsonType: "object", required: ["name"] } } })
            133	collection-collmod-index-hidden	db.runCommand({ collMod: "scratch", index: { name: "hideMe_1", hidden: true } })
            134	collection-list-search-indexes-command	db.runCommand({ listSearchIndexes: "orders" })
            135	command-buildinfo-serverstatus	db.adminCommand({ buildInfo: 1 }); db.adminCommand({ serverStatus: 1 })
            136	command-ping	db.adminCommand({ ping: 1 })
            137	command-hello	db.adminCommand({ hello: 1 })
            138	command-listdatabases	db.adminCommand({ listDatabases: 1 })
            139	command-connectionstatus	db.adminCommand({ connectionStatus: 1, showPrivileges: false })
            140	command-dbstats	db.runCommand({ dbStats: 1 })
            141	command-collstats	db.runCommand({ collStats: "orders" })
            142	command-hostinfo	db.adminCommand({ hostInfo: 1 })
            143	command-getcmdlineopts	db.adminCommand({ getCmdLineOpts: 1 })
            144	command-getparameter-fcv	db.adminCommand({ getParameter: 1, featureCompatibilityVersion: 1 })
            145	command-currentop	db.adminCommand({ currentOp: 1, active: true })
            146	command-top	db.adminCommand({ top: 1 })
            147	command-profile-get	db.runCommand({ profile: -1 })
            148	command-listcommands	db.adminCommand({ listCommands: 1 })
            149	command-usersinfo	db.adminCommand({ usersInfo: 1 })
            150	command-rolesinfo	db.adminCommand({ rolesInfo: 1 })
            151	command-replset-get-status	db.adminCommand({ replSetGetStatus: 1 })
            152	command-list-shards	db.adminCommand({ listShards: 1 })
            153	command-get-default-rw-concern	db.adminCommand({ getDefaultRWConcern: 1 })
            154	command-validate	db.runCommand({ validate: "orders", full: false })
            155	command-plan-cache-clear	db.runCommand({ planCacheClear: "orders" })
            156	command-plan-cache-list	db.runCommand({ planCacheListPlans: "orders", query: { status: "paid" }, sort: {}, projection: {} })
            157	datatype-string	db.types.insertOne({ kind: "datatype-string", value: "text" })
            158	datatype-int32	db.types.insertOne({ kind: "datatype-int32", value: 32 })
            159	datatype-int64	db.types.insertOne({ kind: "datatype-int64", value: NumberLong("64") })
            160	datatype-double	db.types.insertOne({ kind: "datatype-double", value: 3.14 })
            161	datatype-decimal128	db.types.insertOne({ kind: "datatype-decimal128", value: NumberDecimal("12.34") })
            162	datatype-boolean	db.types.insertOne({ kind: "datatype-boolean", value: true })
            163	datatype-date	db.types.insertOne({ kind: "datatype-date", value: new Date() })
            164	datatype-array	db.types.insertOne({ kind: "datatype-array", value: ["a", "b"] })
            165	datatype-document	db.types.insertOne({ kind: "datatype-document", value: { nested: true } })
            166	datatype-null	db.types.insertOne({ kind: "datatype-null", value: null })
            167	datatype-objectid	db.types.insertOne({ kind: "datatype-objectid", value: ObjectId() })
            168	datatype-binary	db.types.insertOne({ kind: "datatype-binary", value: BinData(0, "AQID") })
            169	datatype-timestamp	db.types.insertOne({ kind: "datatype-timestamp", value: Timestamp() })
            170	datatype-regex	db.types.insertOne({ kind: "datatype-regex", value: /^compat/i })
            171	datatype-min-key	db.types.insertOne({ kind: "datatype-min-key", value: MinKey() })
            172	datatype-max-key	db.types.insertOne({ kind: "datatype-max-key", value: MaxKey() })
            173	geospatial-2dsphere-index	db.places.createIndex({ location: "2dsphere" })
            174	geospatial-geo-within	db.places.countDocuments({ location: { $geoWithin: { $geometry: { type: "Polygon", coordinates: [[[116,39],[117,39],[117,40.5],[116,40.5],[116,39]]] } } } })
            175	geospatial-near	db.places.find({ location: { $near: { $geometry: { type: "Point", coordinates: [116.397, 39.908] }, $maxDistance: 100000 } } }).limit(1)
            176	geospatial-geo-intersects	db.places.countDocuments({ area: { $geoIntersects: { $geometry: { type: "Point", coordinates: [116.397, 39.908] } } } })
            177	transaction-commit	session.startTransaction(); db.events.insertOne(...); db.customers.updateOne(...); session.commitTransaction()
            178	transaction-abort	session.startTransaction(); db.events.insertOne(...); session.abortTransaction()
            179	transaction-read-your-writes	session.startTransaction(); db.events.insertOne(...); db.events.countDocuments(...); session.commitTransaction()
            180	change-stream-open	const cursor = db.events.watch(); db.events.insertOne({ type: "change-stream", at: new Date() }); cursor.hasNext()
            181	change-stream-pipeline	db.events.watch([{ $match: { "fullDocument.type": "change-stream-pipeline" } }])
            182	change-stream-full-document	db.events.watch([], { fullDocument: "updateLookup" })
            """;
}
